---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  APP_NAME: fec | api | feature
services:
  - fec-s3-feature
  - fec-redis
  - fec-api-elasticsearch
  - fec-creds-feature
applications:
  - name: celery-worker
    instances: 2
    memory: 1G
    disk_quota: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 2
